---
title: "Fantasy Football Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: default
    orientation: columns
---

```{r setup, include=FALSE}

#Load required libraries
if (!require(readxl)) install.packages('readxl')
if (!require(tidyverse)) install.packages('tidyverse')
if (!require(plotly)) install.packages('plotly')
if (!require(htmlwidgets)) install.packages('htmlwidgets')
if (!require(magick)) install.packages('magick')
if (!require(gt)) install.packages('gt')
if (!require(gtExtras)) install.packages('gtExtras')
if (!require(DT)) install.packages('DT')
if (!require(ggrepel)) install.packages('ggrepel')

library(readxl)
library(tidyverse)
library(plotly)
library(htmlwidgets)
library(magick)
library(gt)
library(gtExtras)
library(DT)
library(ggrepel)

# Read in data
FFL_Table <- read_excel("FFL_Data.xlsx", sheet = "Min Table") %>%
  # Add a win column if points for are greater than points against
  mutate(Win = ifelse(`Points For` > `Points Against`, 1, 0)) %>%
  # Group by team
  group_by(Team) %>%
  # Add cumulative win count and cumulative points for/against columns
  summarize(Win = Win,
            Wins = cumsum(Win),
            Week = Week,
            `Points For` = `Points For`,
            `Points Against` = `Points Against`,
            `Cumulative Points For` = round(cumsum(`Points For`), digits = 1),
            `Cumulative Points Against` = round(cumsum(`Points Against`), digits = 1),
    Image = Image) %>%
  # Group by team and week
  group_by(Team, Week) %>%
  # Add a win-loss variable, win percentage, and keep the rest
  summarize(
    Win = Win, 
    `W-L` = paste0(Wins, "-", parse_number(Week)-Wins),
    `Win Percentage` = 100*(round(Wins/parse_number(Week), digits = 3)),
    `Points For` = `Points For`,
    `Points Against` = `Points Against`,
    `Cumulative Points For` = `Cumulative Points For`,
    `Cumulative Points Against` = `Cumulative Points Against`,
    Image = Image) %>%
  # Group by week
  group_by(Week) %>%
  # Arrange by win percentage then cumulative points for (descending order)
  arrange(desc(`Win Percentage`), desc(`Cumulative Points For`)) %>%
  # Add a poisition column based on the arranged data frame
  mutate(Position = 1:12) %>%
  arrange(parse_number(Week), Position)


# Color palette, variables, etc. 
ffl_pal <- c(
  "#327FFF", "#70C624", "#a56f53", "#575b5e", "#3261c2", "#FFB426",  
  "#6c5657", "#0070bf", "#6c53a9", "#4d806e", "#d5af32", "#269F99"
)

current_wk <- paste("Week", max(parse_number(FFL_Table$Week)))

```

```{r all play, echo=FALSE}

# All Play Record
All_Play <- function(Teams, Weeks) {
  
  cbind.data.frame(
    Wins = FFL_Table %>%
      filter(Week == Weeks) %>%
      mutate(Points = .[.$Team == Teams, ]$`Points For`,
             Difference = Points - `Points For`,
             AP_Win = ifelse(Difference > 0, 1, 0)) %>%
      .$AP_Win %>%
      sum(),
    Teams,
    Weeks
  )}


Teams <- FFL_Table$Team 
Weeks <- FFL_Table$Week


AP_DF <- map2(
  .x = Teams,
  .y = Weeks,
  .f = All_Play
) %>%
  bind_rows()


AP_Tbl <- left_join(
  AP_DF %>%
    group_by(Teams) %>%
    summarise(
      `Total Wins` = sum(Wins),
      `Total Games` = parse_number(current_wk)*11,
      `Win Percentage` = round(`Total Wins`/`Total Games`, digits = 4)) %>%
    arrange(desc(`Total Wins`)),
  FFL_Table %>%
    group_by(Team) %>%
    summarize(Percentage = sum(Win)/parse_number(current_wk)),
  by = c("Teams" = "Team")) %>%
  mutate(Difference = scales::percent(Percentage - `Win Percentage`),
         `Win Percentage` = scales::percent(`Win Percentage`),
         Percentage = scales::percent(Percentage))

colnames(AP_Tbl) <- c("Team", "All Play Wins", "All Play Games", 
                      "All Play Percent", "Actual Percent", "Difference")

```

# League Table

## Row

<br>

#### 

```{r new gt, echo=FALSE, warning=FALSE}

# Write a function to retrieve the last 5 outcomes for a single team
Last_Five <- function(team, week, col_var) {
  
  outcome_list <- FFL_Table %>%
    filter(Team == team, parse_number(Week) > week)
  
  outcome_list <- outcome_list[[col_var]] 
  
  outcome_list <- tibble(
    Team = team, 
    L5 = list(outcome_list))
  
}

# Iterate over all teams to find last 5 wins and last 5 points for
L5_Wins <- pmap(
  .l = list(
    team = unique(FFL_Table$Team),
    week = parse_number(current_wk)-5,
    "Win"),
  .f = Last_Five) %>%
  bind_rows()

L5_Pts <- pmap(
  .l = list(
    team = unique(FFL_Table$Team),
    week = parse_number(current_wk)-5,
    "Points For"),
  .f = Last_Five) %>%
  bind_rows()


# Define max and min values for Points For and Points Against
max_PF <- max(FFL_Table[FFL_Table$Week == current_wk, ]$`Cumulative Points For`)
min_PF <- min(FFL_Table[FFL_Table$Week == current_wk, ]$`Cumulative Points For`)
max_PA <- max(FFL_Table[FFL_Table$Week == current_wk, ]$`Cumulative Points Against`)
min_PA <- min(FFL_Table[FFL_Table$Week == current_wk, ]$`Cumulative Points Against`)


# Generate the gt table
FFL_Table %>%
  filter(Week == current_wk) %>% ungroup() %>%
  left_join(L5_Wins, by = "Team") %>%
  left_join(L5_Pts, by = "Team") %>%
  left_join(AP_Tbl %>% select(Team, `All Play Percent`), by = "Team") %>%
  select(Position, Image, Team, `W-L`, `Win Percentage`, `All Play Percent`, 
         `Cumulative Points For`, `Cumulative Points Against`, "L5 Games" = L5.x, "L5 Points" = L5.y) %>%
  mutate(`Win Percentage` = scales::percent(`Win Percentage`/100, accuracy = 0.1)) %>%
  # Generate the gt() table
  gt() %>%
  # Color the points for column based on min and max values
  data_color(
    columns = c(`Cumulative Points For`),
    colors = scales::col_numeric(
      palette = c("#eb633d", "#ebae34", "#b6eb60", "#0bb83c"),
      domain = c(min_PF, max_PF)),
    alpha = 0.7) %>%
  # Color the points against column based on min and max values
  data_color(
    columns = c(`Cumulative Points Against`),
    colors = scales::col_numeric(
      palette = c("#0bb83c", "#b6eb60", "#ebae34", "#eb633d"),
      domain = c(min_PA, max_PA)),
    alpha = 0.7) %>%
  # Add the win-loss column based on the L5 games list
  gt_plt_winloss(`L5 Games`, palette = c("#0bb83c", "#eb633d", "#edf0f0"), max_wins = 5) %>%
  # Add a sparkline for the points from the last five games
  gt_plt_sparkline(`L5 Points`, type = "ref_mean", same_limit = TRUE,
                   palette = c("#3d3b3b", "#3d3b3b", "#eb633d", "#0bb83c", "#8a8787")) %>%
  # Bold the team name column
  tab_style(
    style = list(cell_text(weight = "bold")),
    locations = cells_body(columns = 3)) %>%
  tab_style(
    style = list(cell_text(color = "#2b2b2b")),
    locations = cells_body(columns = 4:8)) %>%
  # Adjust column widths for better aesthetics 
  cols_width(
    columns = 1 ~ px(50),
    columns = 2 ~ px(40),
    columns = 3 ~ px(260),
    columns = 4:9 ~ px(100),
    columns = 10 ~px(140)) %>%
  # Update column names
  cols_label(
    `Cumulative Points For` = "Points For",
    `Cumulative Points Against` = "Points Against",
    Position = "",
    Image = "") %>% 
  # Align the columns, centered except the team name
  cols_align(
    align = "center",
    columns = c(1:2, 4:10)) %>%
  # Add icons using text transform
  text_transform(
    locations = cells_body(columns = Image),
    fn = function(x) {
      local_image(
        filename = FFL_Table[FFL_Table$Week == current_wk, ]$Image,
        height = 25)
    }) %>%
  tab_header(
    title = "League Standings",
    subtitle = "Beta Hetas and a Worm") %>%
  gt_theme_guardian()

```

# Position by Week

## Row

### 

```{r plotly, warning=FALSE, echo=FALSE, fig.align = 'center'}

# create the base plot using ggplot
ffl_img <- FFL_Table %>%
  ggplot(aes(x = factor(Week, level = paste("Week", 1:16)), 
             y = Position, group = Team)) +
  geom_hline(yintercept = 6.5, linetype = "dashed", color = "gray", size = 0.3) +
  geom_point(aes(color = Team,
                 text = paste0("<b>", Team, "</b>",  
                               "<br>",
                               "<br>Position: ", Position,
                               "<br>Record (Win %): ", `W-L`, " (", scales::percent(`Win Percentage`/100), ")",
                               "<br>Points For: ", `Points For`,
                               "<br>Points Against: ", `Points Against`,
                               "<br>",
                               "<br>Cumulative Points For: ", `Cumulative Points For`,
                               "<br>Cumulative Points Against: ", `Cumulative Points Against`))) +
  geom_line(aes(color = Team), size = 1) +
  scale_color_manual(values = ffl_pal) +
  scale_y_continuous(breaks = (seq(from = 1, to = 12, by = 1)),
                     labels = c(seq(from = 1, to = 12, by = 1))) +
  labs(title = "Position by Week") +
  theme_classic() +
  guides(size = "none") +
  theme(axis.line.x = element_line(color = "#3b3d3d", size = 1, linetype = "solid"),
        axis.line.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid.major.y = element_line(linetype = "dashed", color = "#ECE6E4"),
        aspect.ratio = 1) 


# Add images at current week
mdf <- FFL_Table %>% 
  filter(Week == current_wk) 


ig = lapply(1:nrow(mdf),
            function(i){
              
              img <- image_read(mdf[i,]$Image) %>% as.raster()
              
              list(source = raster2uri(img),
                   xref = "paper", yref = "y",
                   xanchor = "center", yanchor = "middle",
                   x = 0.94,
                   y = mdf[i, ]$Position,
                   sizex = 0.5, sizey = 0.5)
            })

# Use ggplotly to add interactivity
ggplotly(ffl_img, tooltip = "text") %>%
  layout(images = ig) %>%
  config(modeBarButtonsToRemove = c("pan2d", "autoScale2d", "zoom2d", "zoomIn2d", "zoomOut2d")) %>% 
  config(displaylogo = FALSE) %>% 
  onRender("function(el, x) {Plotly.d3.select('.cursor-pointer').style('cursor', 'pointer')}") %>%
  layout(xaxis = list(fixedrange = TRUE), 
         yaxis = list(fixedrange = TRUE, autorange = "reversed")) %>%
  layout(title = list(text = paste0('<b>Position by Week</b>'), 
                      font = list(color = "#392c3b", size = 16), 
                      xanchor = "left", x = 0.05, y = 0.95), 
         legend = list(x = 1.1, y = 0.5, bgcolor = "#fafaf7"), 
         margin = list(pad = 10),
         paper_bgcolor = "#fafaf7", 
         plot_bgcolor = "#fafaf7", 
         font = list(size = 11, color = "#392c3b", family = "Arial")) 

```

# Quadrant Chart

## Row

<br>

### 

```{r xy scatter}

scatter_df <- FFL_Table %>%
  filter(Week == current_wk) %>%
  select(Team, `Cumulative Points For`, `Cumulative Points Against`, Position)

# Find the mid point (average) and create low and high ranges for the plot
mid_pt <- round(mean(scatter_df$`Cumulative Points For`), digits = 0)
low_range <- mid_pt - 200
high_range <- mid_pt + 200


# Create the scatter plot
scatter_df %>%
  # Generate new column with four quadrants based on the mid point (average)
  mutate(Quadrant = case_when(`Cumulative Points For` > mid_pt & `Cumulative Points Against` > mid_pt   ~ "Q1",
                              `Cumulative Points For` <= mid_pt & `Cumulative Points Against` > mid_pt  ~ "Q2",
                              `Cumulative Points For` <= mid_pt & `Cumulative Points Against` <= mid_pt ~ "Q3",
                              TRUE ~ "Q4"),
         # Generate new label column that takes the first 1-2 words in Team and adds position in ()
         Label = map(.x = Team, .f = function(x) {
           ifelse(nchar(unlist(strsplit(x, " "))[[1]]) > 3,
                  paste0(unlist(strsplit(x, " "))[[1]], 
                         " (", scatter_df[scatter_df$Team == x, ]$Position, ")"),
                  paste0(unlist(strsplit(x, " "))[[1]], " ", unlist(strsplit(x, " "))[[2]], 
                         " (", scatter_df[scatter_df$Team == x, ]$Position, ")" ))
           
         })) %>%
  ggplot(aes(`Cumulative Points Against`, `Cumulative Points For`, label = Label, color = Quadrant)) +
  geom_hline(yintercept = mid_pt, color = "#4d4e4f", linetype = "dotted", size = 1) +
  geom_vline(xintercept = mid_pt, color = "#4d4e4f", linetype = "dotted", size = 1) +
  geom_point(size = 3) +
  scale_color_manual(values = c("#b6eb60", "#eb633d", "#ebae34","#0bb83c")) +
  geom_label_repel(aes(color = Quadrant), size = 3, fill = "white", 
                   min.segment.length = unit(0, "lines"), fontface = "bold") +
  scale_y_continuous(limits = c(low_range, high_range), 
                     breaks = c(low_range + 100, mid_pt, high_range - 100),
                     labels = c("Below Average \n Points For", 
                                paste(scales::number(mid_pt, big.mark = ","), "\nPoints"),
                                "Above Average \n Points For")) +
  scale_x_continuous(limits = c(low_range, high_range), 
                     breaks = c(low_range + 100, mid_pt, high_range - 100),
                     labels = c("Below Average \n Points Against", 
                                paste(scales::number(mid_pt, big.mark = ","), "\nPoints"),
                                "Above Average \n Points Against")) +
  coord_fixed(ratio = 1, clip = 'off') +
  theme_classic() +
  labs(x = "", y = "", title = "Quadrant Chart", subtitle = "Points For vs Points Against") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        axis.line = element_line(colour = "#4d4e4f", size = 1),
        axis.text = element_text(face = c('bold', 'plain','bold'), size = c(9, 8, 9)),
        panel.background = element_rect(fill = "#f5f4f0"),
        panel.border = element_rect(color = "#4d4e4f", fill = NA, size = 1))

```

# Box Plot

## Row

<br>

### 

```{r boxplot}

median_pts <- round(median(FFL_Table$`Points For`), digits = 2)

FFL_Table %>%
  ggplot(aes(x = fct_reorder(Team, `Points For`, .fun = 'median'), 
             y = `Points For`, fill = Team)) +
  geom_hline(yintercept = median_pts, color = "#5f6161", size = 1) +
  geom_boxplot(alpha = 1) + 
  scale_fill_manual(values = ffl_pal) +
  coord_flip() +
  theme_classic() +
  labs(title = "Points Boxplot", subtitle = paste0("[Median Points/Game is ", median_pts, "]")) +
  guides(fill = "none") +
  theme(legend.position = "none",
        plot.title = element_text(hjust = 0.5, color = "#5f6161"),
        plot.subtitle = element_text(hjust = 0.5, color = "#5f6161"),
        axis.line.x = element_line(color = "#5f6161", size = 1, linetype = "solid"),
        axis.line.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.background = element_rect(fill = "#f5f4f0"),
        panel.grid.major.y = element_line(linetype = "dashed", color = "white"),
        aspect.ratio = 1) 

```

# Schedules - What If?

## Row

<br>

### 

```{r}

# Create a function that one team and another team's schedule and finds win percentage
What_If <- function(team, schedule) {
  
  cbind.data.frame(
    Team_Pts = FFL_Table %>% filter(Team == team) %>% .$`Points For`,
    Schedule_Pts = FFL_Table %>% filter(Team == schedule) %>% .$`Points Against`) %>%
    mutate(Win = ifelse(Team_Pts > Schedule_Pts, 1, ifelse(Team_Pts == Schedule_Pts, NA, 0))) %>%
    drop_na(Win) %>%
    summarize(`Win Percentage` = round(sum(Win)/n(), digits = 3)) %>%
    mutate("Team" = team, "Schedule" = schedule) 
  
}

# Apply the above function to every team x team possibility 
WI_df <- map2(.x = expand.grid(unique(FFL_Table$Team), unique(FFL_Table$Team))$Var1,
              .y = expand.grid(unique(FFL_Table$Team), unique(FFL_Table$Team))$Var2,
              .f = What_If) %>%
  bind_rows()


# Subtitle text 
sub_txt <- "Wondering how the schedule shuffle changed our fate? This table shows what each teams' record (win percentage) would be if they played other teams' schedules. It omits any games they would have played against themselves. The teams are arranged by mean schedule win percentage. Wait, what's that? You also noticed that our league commissioner has the softest schedule. It's a little weird, right. I mean it's statistically possible, but definitely gives us the right to speculate wildly. Is this league rigged? Could be. How far up to does this go!? Maybe higher than you think. Kickbacks from Yahoo? Sure. Related to that new Twitter drama? It's possible. The point is, this What If Analysis helps your imagination run free. Enjoy!"


# Find the schedules ranking order (easiest to hardest) 
schedule_rank <- WI_df %>%
  group_by(Schedule) %>%
  summarize(Mean = mean(`Win Percentage`)) %>%
  arrange(desc(Mean)) %>%
  .$Schedule %>%
  as.character()


# Pivot wider and generate the gt() table
WI_df %>%
  pivot_wider(names_from = Team, values_from = `Win Percentage`) %>%
  select(Schedule, schedule_rank) %>%
  arrange(factor(Schedule, levels = schedule_rank)) %>%
  gt() %>%
  data_color(
    columns = 2:13,
    colors = scales::col_numeric(
      palette = c("#eb633d", "#ebae34", "#b6eb60", "#0bb83c"),
      domain = c(0, 1)),
    alpha = 0.8) %>%
  tab_style(
    style = list(cell_text(weight = "bold")),
    locations = cells_body(columns = 1)) %>%
  cols_width(
    columns = 1 ~ px(200),
    columns = 2:13 ~ px(60)) %>%
  cols_align(
    align = "center",
    columns = c(2:13)) %>%
  cols_align(
    align = "left",
    columns = c(1)) %>%
  fmt_percent(
    columns = c(2:13),
    decimals = 1) %>%
    tab_header(
    title = "Schedule - What if Analysis",
    subtitle = sub_txt) %>%
  gt_theme_espn() %>%
    tab_style(
    style = list(cell_text(color = "#2b2b2b")),
    locations = cells_body(columns = 2:13)) %>%
  tab_options(
    table.font.size = '12px') 

```

# Extras

<br>

**Under Construction...**

## Row

<br>

### 

```{r DT}

FFL_Table %>% 
  select(-Win, -Image) %>% 
  arrange(Week, Position) %>%
  datatable(extensions = 'Buttons', rownames = FALSE, filter = 'top', 
            options = list(buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           columnDefs = list(list(className = 'dt-center', targets = 2:8)),
                           pageLength = 12, 
                           autowidth = TRUE,
                           dom = 'Blfrtip'))

```

```{r highlight, include=FALSE}

hi_lite <- highlight_key(FFL_Table %>%
                           cbind.data.frame(
                             Date = rep(seq.Date(from = as.Date("2022/09/11"), by = "weeks", 
                                                 length.out = max(parse_number(FFL_Table$Week))), each = 12)) %>%
                           select(Team, Date, Position), 
                         ~Team)


ig2 = lapply(1:nrow(mdf),
            function(i){
              
              img <- image_read(mdf[i,]$Image) %>% as.raster()
              
              list(source = raster2uri(img),
                   xref = "paper", yref = "y",
                   xanchor = "center", yanchor = "middle",
                   x = 1,
                   y = mdf[i, ]$Position,
                   sizex = 0.5, sizey = 0.5)
            })


hi_lite %>%
  plot_ly(x = ~Date, y = ~Position, color = ~Team, mode = "lines", colors = ffl_pal) %>%
  add_trace(line = list(shape = "spline", width = 8), name = ~Team) %>%
  layout(images = ig2) %>%
  layout(xaxis = list(rangeslider = list(visible = TRUE),
                      rangeselector = list(
                        buttons = list(
                          list(count = 7, label = "Week", step = "day", stepmode = "backward"),
                          list(count = 1, label = "Month", step = "month", stepmode = "backward"),
                          list(step = "all")
                        ))),
         showlegend = TRUE,
         yaxis = list(dtick = 1, autorange = "reversed")) %>%
  highlight(on = "plotly_click", off = "plotly_doubleclick", color = NULL, opacityDim = 0.4) %>%
  config(modeBarButtonsToRemove = c("pan2d", "autoScale2d", "zoom2d", "zoomIn2d", "zoomOut2d")) %>% 
  config(displaylogo = FALSE) %>% 
  onRender("function(el, x) {Plotly.d3.select('.cursor-pointer').style('cursor', 'pointer')}") %>%
  layout(xaxis = list(fixedrange = TRUE), 
         yaxis = list(fixedrange = TRUE, autorange = "reversed")) %>%
  layout(title = list(#text = paste0('<b>Position by Week</b>'), 
    font = list(color = "#392c3b", size = 16), 
    xanchor = "left", x = 0.05, y = 0.95), 
    legend = list(x = 1.1, y = 0.5, bgcolor = "#fafaf7"), 
    margin = list(pad = 10),
    paper_bgcolor = "#fafaf7", 
    plot_bgcolor = "#fafaf7", 
    font = list(size = 11, color = "#392c3b", family = "Arial")) 

```
